 * Serving Flask app "client" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Serving Flask app "client" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Serving Flask app "client" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:6000/ (Press CTRL+C to quit)
 * Running on http://0.0.0.0:6001/ (Press CTRL+C to quit)
 * Running on http://0.0.0.0:6002/ (Press CTRL+C to quit)
127.0.0.1 - - [28/Apr/2022 10:44:59] "[37mPOST /transactions/new HTTP/1.1[0m" 200 -
127.0.0.1 - - [28/Apr/2022 10:44:59] "[37mGET /mine HTTP/1.1[0m" 200 -
127.0.0.1 - - [28/Apr/2022 10:44:59] "[37mGET //chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [28/Apr/2022 10:44:59] "[37mGET //chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [28/Apr/2022 10:44:59] "[37mGET /resolve HTTP/1.1[0m" 200 -
127.0.0.1 - - [28/Apr/2022 10:44:59] "[37mGET /chain HTTP/1.1[0m" 200 -
 * Serving Flask app "shuffle_server" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Serving Flask app "client" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:6004/ (Press CTRL+C to quit)
 * Serving Flask app "client" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:6001/ (Press CTRL+C to quit)
 * Running on http://0.0.0.0:6000/ (Press CTRL+C to quit)
127.0.0.1 - - [28/Apr/2022 10:46:32] "[37mPOST /coinshuffle/submitkey HTTP/1.1[0m" 201 -
127.0.0.1 - - [28/Apr/2022 10:46:32] "[37mPOST /coinshuffle/new HTTP/1.1[0m" 201 -
127.0.0.1 - - [28/Apr/2022 10:46:33] "[37mPOST /coinshuffle/submitkey HTTP/1.1[0m" 201 -
127.0.0.1 - - [28/Apr/2022 10:46:33] "[37mPOST /coinshuffle/new HTTP/1.1[0m" 201 -
[2022-04-28 10:46:33,046] ERROR in app: Exception on /coinshuffle/initiate [POST]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/llopin/.local/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/llopin/.local/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/llopin/Projects/coinshuffle/client.py", line 109, in post
    node.coin_shuffler.start(json.loads(args['peers']), json.loads(args['order']))
  File "/home/llopin/Projects/coinshuffle/coin_shuffle.py", line 81, in start
    self.index = int(self._find_index(order))
  File "/home/llopin/Projects/coinshuffle/coin_shuffle.py", line 96, in _find_index
    for i,ek in order.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'
127.0.0.1 - - [28/Apr/2022 10:46:33] "[35m[1mPOST /coinshuffle/initiate HTTP/1.1[0m" 500 -
[2022-04-28 10:46:33,059] ERROR in app: Exception on /coinshuffle/initiate [POST]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/llopin/.local/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/llopin/.local/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/llopin/Projects/coinshuffle/client.py", line 109, in post
    node.coin_shuffler.start(json.loads(args['peers']), json.loads(args['order']))
  File "/home/llopin/Projects/coinshuffle/coin_shuffle.py", line 81, in start
    self.index = int(self._find_index(order))
  File "/home/llopin/Projects/coinshuffle/coin_shuffle.py", line 96, in _find_index
    for i,ek in order.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'
127.0.0.1 - - [28/Apr/2022 10:46:33] "[35m[1mPOST /coinshuffle/initiate HTTP/1.1[0m" 500 -
127.0.0.1 - - [28/Apr/2022 10:46:33] "[37mGET /coinshuffle/start HTTP/1.1[0m" 200 -
127.0.0.1 - - [28/Apr/2022 10:46:33] "[37mGET /mine HTTP/1.1[0m" 200 -
127.0.0.1 - - [28/Apr/2022 10:46:33] "[37mGET /chain HTTP/1.1[0m" 200 -
 * Serving Flask app "shuffle_server" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:6004/ (Press CTRL+C to quit)
 * Serving Flask app "client" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:6000/ (Press CTRL+C to quit)
 * Serving Flask app "client" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:6001/ (Press CTRL+C to quit)
127.0.0.1 - - [28/Apr/2022 10:47:07] "[37mPOST /coinshuffle/submitkey HTTP/1.1[0m" 201 -
127.0.0.1 - - [28/Apr/2022 10:47:07] "[37mPOST /coinshuffle/new HTTP/1.1[0m" 201 -
127.0.0.1 - - [28/Apr/2022 10:47:08] "[37mPOST /coinshuffle/submitkey HTTP/1.1[0m" 201 -
127.0.0.1 - - [28/Apr/2022 10:47:08] "[37mPOST /coinshuffle/new HTTP/1.1[0m" 201 -
[2022-04-28 10:47:08,094] ERROR in app: Exception on /coinshuffle/initiate [POST]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/llopin/.local/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/llopin/.local/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/llopin/Projects/coinshuffle/client.py", line 109, in post
    node.coin_shuffler.start(json.loads(args['peers']), json.loads(args['order']))
  File "/home/llopin/Projects/coinshuffle/coin_shuffle.py", line 81, in start
    self.index = int(self._find_index(order))
  File "/home/llopin/Projects/coinshuffle/coin_shuffle.py", line 96, in _find_index
    for i,ek in order.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'
127.0.0.1 - - [28/Apr/2022 10:47:08] "[35m[1mPOST /coinshuffle/initiate HTTP/1.1[0m" 500 -
[2022-04-28 10:47:08,099] ERROR in app: Exception on /coinshuffle/initiate [POST]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/llopin/.local/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/llopin/.local/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/llopin/Projects/coinshuffle/client.py", line 109, in post
    node.coin_shuffler.start(json.loads(args['peers']), json.loads(args['order']))
  File "/home/llopin/Projects/coinshuffle/coin_shuffle.py", line 81, in start
    self.index = int(self._find_index(order))
  File "/home/llopin/Projects/coinshuffle/coin_shuffle.py", line 96, in _find_index
    for i,ek in order.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'
127.0.0.1 - - [28/Apr/2022 10:47:08] "[35m[1mPOST /coinshuffle/initiate HTTP/1.1[0m" 500 -
127.0.0.1 - - [28/Apr/2022 10:47:08] "[37mGET /coinshuffle/start HTTP/1.1[0m" 200 -
127.0.0.1 - - [28/Apr/2022 10:47:08] "[37mGET /mine HTTP/1.1[0m" 200 -
127.0.0.1 - - [28/Apr/2022 10:47:08] "[37mGET /chain HTTP/1.1[0m" 200 -
 * Serving Flask app "shuffle_server" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Serving Flask app "client" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:6004/ (Press CTRL+C to quit)
 * Serving Flask app "client" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:6000/ (Press CTRL+C to quit)
 * Running on http://0.0.0.0:6001/ (Press CTRL+C to quit)
127.0.0.1 - - [28/Apr/2022 10:56:54] "[37mPOST /coinshuffle/submitkey HTTP/1.1[0m" 201 -
127.0.0.1 - - [28/Apr/2022 10:56:54] "[37mPOST /coinshuffle/new HTTP/1.1[0m" 201 -
127.0.0.1 - - [28/Apr/2022 10:56:54] "[37mPOST /coinshuffle/submitkey HTTP/1.1[0m" 201 -
127.0.0.1 - - [28/Apr/2022 10:56:54] "[37mPOST /coinshuffle/new HTTP/1.1[0m" 201 -
[2022-04-28 10:56:54,425] ERROR in app: Exception on /coinshuffle/initiate [POST]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/llopin/.local/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/llopin/.local/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/llopin/Projects/coinshuffle/client.py", line 109, in post
    node.coin_shuffler.start(json.loads(args['peers']), json.loads(args['order']))
  File "/home/llopin/Projects/coinshuffle/coin_shuffle.py", line 81, in start
    self.index = int(self._find_index(order))
  File "/home/llopin/Projects/coinshuffle/coin_shuffle.py", line 96, in _find_index
    for i,ek in order.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'
127.0.0.1 - - [28/Apr/2022 10:56:54] "[35m[1mPOST /coinshuffle/initiate HTTP/1.1[0m" 500 -
[2022-04-28 10:56:54,429] ERROR in app: Exception on /coinshuffle/initiate [POST]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/llopin/.local/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/llopin/.local/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/llopin/Projects/coinshuffle/client.py", line 109, in post
    node.coin_shuffler.start(json.loads(args['peers']), json.loads(args['order']))
  File "/home/llopin/Projects/coinshuffle/coin_shuffle.py", line 81, in start
    self.index = int(self._find_index(order))
  File "/home/llopin/Projects/coinshuffle/coin_shuffle.py", line 96, in _find_index
    for i,ek in order.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'
127.0.0.1 - - [28/Apr/2022 10:56:54] "[35m[1mPOST /coinshuffle/initiate HTTP/1.1[0m" 500 -
127.0.0.1 - - [28/Apr/2022 10:56:54] "[37mGET /coinshuffle/start HTTP/1.1[0m" 200 -
127.0.0.1 - - [28/Apr/2022 10:56:54] "[37mGET /mine HTTP/1.1[0m" 200 -
127.0.0.1 - - [28/Apr/2022 10:56:54] "[37mGET /chain HTTP/1.1[0m" 200 -
 * Serving Flask app "shuffle_server" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Serving Flask app "client" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Serving Flask app "client" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:6004/ (Press CTRL+C to quit)
 * Running on http://0.0.0.0:6001/ (Press CTRL+C to quit)
 * Running on http://0.0.0.0:6000/ (Press CTRL+C to quit)
127.0.0.1 - - [28/Apr/2022 11:44:03] "[37mPOST /coinshuffle/submitkey HTTP/1.1[0m" 201 -
127.0.0.1 - - [28/Apr/2022 11:44:03] "[37mPOST /coinshuffle/new HTTP/1.1[0m" 201 -
127.0.0.1 - - [28/Apr/2022 11:44:03] "[37mPOST /coinshuffle/submitkey HTTP/1.1[0m" 201 -
127.0.0.1 - - [28/Apr/2022 11:44:03] "[37mPOST /coinshuffle/new HTTP/1.1[0m" 201 -
[2022-04-28 11:44:03,527] ERROR in app: Exception on /coinshuffle/initiate [POST]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/llopin/.local/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/llopin/.local/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/llopin/Projects/coinshuffle/client.py", line 109, in post
    node.coin_shuffler.start(json.loads(args['peers']), json.loads(args['order']))
  File "/home/llopin/Projects/coinshuffle/coin_shuffle.py", line 83, in start
    self.encrypted_target = self._encrypt_dest()
  File "/home/llopin/Projects/coinshuffle/coin_shuffle.py", line 119, in _encrypt_dest
    t = util.encrypt(self.order[str(i)], t)
  File "/home/llopin/Projects/coinshuffle/util.py", line 26, in encrypt
    return hexlify(RSA.importKey(unhexlify(str(epkey))).encrypt(str(msg), 'x')[0])
  File "/home/llopin/.local/lib/python3.9/site-packages/Crypto/PublicKey/RSA.py", line 379, in encrypt
    raise NotImplementedError("Use module Crypto.Cipher.PKCS1_OAEP instead")
NotImplementedError: Use module Crypto.Cipher.PKCS1_OAEP instead
127.0.0.1 - - [28/Apr/2022 11:44:03] "[35m[1mPOST /coinshuffle/initiate HTTP/1.1[0m" 500 -
[2022-04-28 11:44:03,536] ERROR in app: Exception on /coinshuffle/initiate [POST]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/llopin/.local/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/llopin/.local/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/llopin/Projects/coinshuffle/client.py", line 109, in post
    node.coin_shuffler.start(json.loads(args['peers']), json.loads(args['order']))
  File "/home/llopin/Projects/coinshuffle/coin_shuffle.py", line 83, in start
    self.encrypted_target = self._encrypt_dest()
  File "/home/llopin/Projects/coinshuffle/coin_shuffle.py", line 119, in _encrypt_dest
    t = util.encrypt(self.order[str(i)], t)
  File "/home/llopin/Projects/coinshuffle/util.py", line 26, in encrypt
    return hexlify(RSA.importKey(unhexlify(str(epkey))).encrypt(str(msg), 'x')[0])
  File "/home/llopin/.local/lib/python3.9/site-packages/Crypto/PublicKey/RSA.py", line 379, in encrypt
    raise NotImplementedError("Use module Crypto.Cipher.PKCS1_OAEP instead")
NotImplementedError: Use module Crypto.Cipher.PKCS1_OAEP instead
127.0.0.1 - - [28/Apr/2022 11:44:03] "[35m[1mPOST /coinshuffle/initiate HTTP/1.1[0m" 500 -
127.0.0.1 - - [28/Apr/2022 11:44:03] "[37mGET /coinshuffle/start HTTP/1.1[0m" 200 -
127.0.0.1 - - [28/Apr/2022 11:44:03] "[37mGET /mine HTTP/1.1[0m" 200 -
127.0.0.1 - - [28/Apr/2022 11:44:03] "[37mGET /chain HTTP/1.1[0m" 200 -
 * Serving Flask app "client" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Serving Flask app "client" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:6001/ (Press CTRL+C to quit)
 * Running on http://0.0.0.0:6000/ (Press CTRL+C to quit)
 * Serving Flask app "shuffle_server" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:6004/ (Press CTRL+C to quit)
127.0.0.1 - - [28/Apr/2022 13:12:43] "[37mPOST /coinshuffle/submitkey HTTP/1.1[0m" 201 -
127.0.0.1 - - [28/Apr/2022 13:12:43] "[37mPOST /coinshuffle/new HTTP/1.1[0m" 201 -
127.0.0.1 - - [28/Apr/2022 13:12:43] "[37mPOST /coinshuffle/submitkey HTTP/1.1[0m" 201 -
127.0.0.1 - - [28/Apr/2022 13:12:43] "[37mPOST /coinshuffle/new HTTP/1.1[0m" 201 -
[2022-04-28 13:12:43,317] ERROR in app: Exception on /coinshuffle/initiate [POST]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/llopin/.local/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/llopin/.local/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/llopin/Projects/coinshuffle/client.py", line 109, in post
    node.coin_shuffler.start(json.loads(args['peers']), json.loads(args['order']))
  File "/home/llopin/Projects/coinshuffle/coin_shuffle.py", line 83, in start
    self.encrypted_target = self._encrypt_dest()
  File "/home/llopin/Projects/coinshuffle/coin_shuffle.py", line 119, in _encrypt_dest
    t = util.encrypt(self.order[str(i)], t)
  File "/home/llopin/Projects/coinshuffle/util.py", line 26, in encrypt
    return hexlify(RSA.importKey(unhexlify(str(epkey))).encrypt(str(msg), 'x')[0])
  File "/home/llopin/.local/lib/python3.9/site-packages/Crypto/PublicKey/RSA.py", line 379, in encrypt
    raise NotImplementedError("Use module Crypto.Cipher.PKCS1_OAEP instead")
NotImplementedError: Use module Crypto.Cipher.PKCS1_OAEP instead
127.0.0.1 - - [28/Apr/2022 13:12:43] "[35m[1mPOST /coinshuffle/initiate HTTP/1.1[0m" 500 -
[2022-04-28 13:12:43,326] ERROR in app: Exception on /coinshuffle/initiate [POST]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/llopin/.local/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/llopin/.local/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/llopin/Projects/coinshuffle/client.py", line 109, in post
    node.coin_shuffler.start(json.loads(args['peers']), json.loads(args['order']))
  File "/home/llopin/Projects/coinshuffle/coin_shuffle.py", line 83, in start
    self.encrypted_target = self._encrypt_dest()
  File "/home/llopin/Projects/coinshuffle/coin_shuffle.py", line 119, in _encrypt_dest
    t = util.encrypt(self.order[str(i)], t)
  File "/home/llopin/Projects/coinshuffle/util.py", line 26, in encrypt
    return hexlify(RSA.importKey(unhexlify(str(epkey))).encrypt(str(msg), 'x')[0])
  File "/home/llopin/.local/lib/python3.9/site-packages/Crypto/PublicKey/RSA.py", line 379, in encrypt
    raise NotImplementedError("Use module Crypto.Cipher.PKCS1_OAEP instead")
NotImplementedError: Use module Crypto.Cipher.PKCS1_OAEP instead
127.0.0.1 - - [28/Apr/2022 13:12:43] "[35m[1mPOST /coinshuffle/initiate HTTP/1.1[0m" 500 -
127.0.0.1 - - [28/Apr/2022 13:12:43] "[37mGET /coinshuffle/start HTTP/1.1[0m" 200 -
127.0.0.1 - - [28/Apr/2022 13:12:43] "[37mGET /mine HTTP/1.1[0m" 200 -
127.0.0.1 - - [28/Apr/2022 13:12:43] "[37mGET /chain HTTP/1.1[0m" 200 -
 * Serving Flask app "shuffle_server" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Serving Flask app "client" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Serving Flask app "client" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:6000/ (Press CTRL+C to quit)
 * Running on http://0.0.0.0:6004/ (Press CTRL+C to quit)
 * Running on http://0.0.0.0:6001/ (Press CTRL+C to quit)
127.0.0.1 - - [28/Apr/2022 15:02:24] "[37mPOST /coinshuffle/submitkey HTTP/1.1[0m" 201 -
127.0.0.1 - - [28/Apr/2022 15:02:24] "[37mPOST /coinshuffle/new HTTP/1.1[0m" 201 -
127.0.0.1 - - [28/Apr/2022 15:02:24] "[37mPOST /coinshuffle/submitkey HTTP/1.1[0m" 201 -
127.0.0.1 - - [28/Apr/2022 15:02:24] "[37mPOST /coinshuffle/new HTTP/1.1[0m" 201 -
[2022-04-28 15:02:24,549] ERROR in app: Exception on /coinshuffle/initiate [POST]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/llopin/.local/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/llopin/.local/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/llopin/Projects/coinshuffle/client.py", line 109, in post
    node.coin_shuffler.start(json.loads(args['peers']), json.loads(args['order']))
  File "/home/llopin/Projects/coinshuffle/coin_shuffle.py", line 83, in start
    self.encrypted_target = self._encrypt_dest()
  File "/home/llopin/Projects/coinshuffle/coin_shuffle.py", line 119, in _encrypt_dest
    t = util.encrypt(self.order[str(i)], t)
  File "/home/llopin/Projects/coinshuffle/util.py", line 27, in encrypt
    cipher = Cipher_PKCS1_v1_5.new(key_pub)
NameError: name 'Cipher_PKCS1_v1_5' is not defined
127.0.0.1 - - [28/Apr/2022 15:02:24] "[35m[1mPOST /coinshuffle/initiate HTTP/1.1[0m" 500 -
[2022-04-28 15:02:24,558] ERROR in app: Exception on /coinshuffle/initiate [POST]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/llopin/.local/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/llopin/.local/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/llopin/Projects/coinshuffle/client.py", line 109, in post
    node.coin_shuffler.start(json.loads(args['peers']), json.loads(args['order']))
  File "/home/llopin/Projects/coinshuffle/coin_shuffle.py", line 83, in start
    self.encrypted_target = self._encrypt_dest()
  File "/home/llopin/Projects/coinshuffle/coin_shuffle.py", line 119, in _encrypt_dest
    t = util.encrypt(self.order[str(i)], t)
  File "/home/llopin/Projects/coinshuffle/util.py", line 27, in encrypt
    cipher = Cipher_PKCS1_v1_5.new(key_pub)
NameError: name 'Cipher_PKCS1_v1_5' is not defined
127.0.0.1 - - [28/Apr/2022 15:02:24] "[35m[1mPOST /coinshuffle/initiate HTTP/1.1[0m" 500 -
127.0.0.1 - - [28/Apr/2022 15:02:24] "[37mGET /coinshuffle/start HTTP/1.1[0m" 200 -
127.0.0.1 - - [28/Apr/2022 15:02:24] "[37mGET /mine HTTP/1.1[0m" 200 -
127.0.0.1 - - [28/Apr/2022 15:02:24] "[37mGET /chain HTTP/1.1[0m" 200 -
 * Serving Flask app "shuffle_server" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Serving Flask app "client" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Serving Flask app "client" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:6001/ (Press CTRL+C to quit)
 * Running on http://0.0.0.0:6000/ (Press CTRL+C to quit)
 * Running on http://0.0.0.0:6004/ (Press CTRL+C to quit)
127.0.0.1 - - [28/Apr/2022 15:03:04] "[37mPOST /coinshuffle/submitkey HTTP/1.1[0m" 201 -
127.0.0.1 - - [28/Apr/2022 15:03:04] "[37mPOST /coinshuffle/new HTTP/1.1[0m" 201 -
127.0.0.1 - - [28/Apr/2022 15:03:04] "[37mPOST /coinshuffle/submitkey HTTP/1.1[0m" 201 -
127.0.0.1 - - [28/Apr/2022 15:03:04] "[37mPOST /coinshuffle/new HTTP/1.1[0m" 201 -
[2022-04-28 15:03:04,597] ERROR in app: Exception on /coinshuffle/initiate [POST]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/llopin/.local/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/llopin/.local/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/llopin/Projects/coinshuffle/client.py", line 109, in post
    node.coin_shuffler.start(json.loads(args['peers']), json.loads(args['order']))
  File "/home/llopin/Projects/coinshuffle/coin_shuffle.py", line 83, in start
    self.encrypted_target = self._encrypt_dest()
  File "/home/llopin/Projects/coinshuffle/coin_shuffle.py", line 119, in _encrypt_dest
    t = util.encrypt(self.order[str(i)], t)
  File "/home/llopin/Projects/coinshuffle/util.py", line 29, in encrypt
    return hexlify(cipher.encrypt(str(msg).encode()))
  File "/home/llopin/.local/lib/python3.9/site-packages/Crypto/Cipher/PKCS1_v1_5.py", line 107, in encrypt
    raise ValueError("Plaintext is too long.")
ValueError: Plaintext is too long.
127.0.0.1 - - [28/Apr/2022 15:03:04] "[35m[1mPOST /coinshuffle/initiate HTTP/1.1[0m" 500 -
[2022-04-28 15:03:04,605] ERROR in app: Exception on /coinshuffle/initiate [POST]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/llopin/.local/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/llopin/.local/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/llopin/Projects/coinshuffle/client.py", line 109, in post
    node.coin_shuffler.start(json.loads(args['peers']), json.loads(args['order']))
  File "/home/llopin/Projects/coinshuffle/coin_shuffle.py", line 83, in start
    self.encrypted_target = self._encrypt_dest()
  File "/home/llopin/Projects/coinshuffle/coin_shuffle.py", line 119, in _encrypt_dest
    t = util.encrypt(self.order[str(i)], t)
  File "/home/llopin/Projects/coinshuffle/util.py", line 29, in encrypt
    return hexlify(cipher.encrypt(str(msg).encode()))
  File "/home/llopin/.local/lib/python3.9/site-packages/Crypto/Cipher/PKCS1_v1_5.py", line 107, in encrypt
    raise ValueError("Plaintext is too long.")
ValueError: Plaintext is too long.
127.0.0.1 - - [28/Apr/2022 15:03:04] "[35m[1mPOST /coinshuffle/initiate HTTP/1.1[0m" 500 -
127.0.0.1 - - [28/Apr/2022 15:03:04] "[37mGET /coinshuffle/start HTTP/1.1[0m" 200 -
127.0.0.1 - - [28/Apr/2022 15:03:04] "[37mGET /mine HTTP/1.1[0m" 200 -
127.0.0.1 - - [28/Apr/2022 15:03:04] "[37mGET /chain HTTP/1.1[0m" 200 -
 * Serving Flask app "shuffle_server" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:6004/ (Press CTRL+C to quit)
 * Serving Flask app "client" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Serving Flask app "client" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:6000/ (Press CTRL+C to quit)
 * Running on http://0.0.0.0:6001/ (Press CTRL+C to quit)
127.0.0.1 - - [28/Apr/2022 15:23:28] "[37mPOST /coinshuffle/submitkey HTTP/1.1[0m" 201 -
127.0.0.1 - - [28/Apr/2022 15:23:28] "[37mPOST /coinshuffle/new HTTP/1.1[0m" 201 -
127.0.0.1 - - [28/Apr/2022 15:23:28] "[37mPOST /coinshuffle/submitkey HTTP/1.1[0m" 201 -
127.0.0.1 - - [28/Apr/2022 15:23:28] "[37mPOST /coinshuffle/new HTTP/1.1[0m" 201 -
[2022-04-28 15:23:28,826] ERROR in app: Exception on /coinshuffle/initiate [POST]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/llopin/.local/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/llopin/.local/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/llopin/Projects/coinshuffle/client.py", line 109, in post
    node.coin_shuffler.start(json.loads(args['peers']), json.loads(args['order']))
  File "/home/llopin/Projects/coinshuffle/coin_shuffle.py", line 83, in start
    self.encrypted_target = self._encrypt_dest()
  File "/home/llopin/Projects/coinshuffle/coin_shuffle.py", line 119, in _encrypt_dest
    t = util.encrypt(self.order[str(i)], t)
  File "/home/llopin/Projects/coinshuffle/util.py", line 31, in encrypt
    return hexlify(cipher.encrypt(str(msg).encode()))
  File "/home/llopin/.local/lib/python3.9/site-packages/Crypto/Cipher/PKCS1_v1_5.py", line 107, in encrypt
    raise ValueError("Plaintext is too long.")
ValueError: Plaintext is too long.
127.0.0.1 - - [28/Apr/2022 15:23:28] "[35m[1mPOST /coinshuffle/initiate HTTP/1.1[0m" 500 -
[2022-04-28 15:23:28,833] ERROR in app: Exception on /coinshuffle/initiate [POST]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/llopin/.local/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/llopin/.local/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/llopin/Projects/coinshuffle/client.py", line 109, in post
    node.coin_shuffler.start(json.loads(args['peers']), json.loads(args['order']))
  File "/home/llopin/Projects/coinshuffle/coin_shuffle.py", line 83, in start
    self.encrypted_target = self._encrypt_dest()
  File "/home/llopin/Projects/coinshuffle/coin_shuffle.py", line 119, in _encrypt_dest
    t = util.encrypt(self.order[str(i)], t)
  File "/home/llopin/Projects/coinshuffle/util.py", line 31, in encrypt
    return hexlify(cipher.encrypt(str(msg).encode()))
  File "/home/llopin/.local/lib/python3.9/site-packages/Crypto/Cipher/PKCS1_v1_5.py", line 107, in encrypt
    raise ValueError("Plaintext is too long.")
ValueError: Plaintext is too long.
127.0.0.1 - - [28/Apr/2022 15:23:28] "[35m[1mPOST /coinshuffle/initiate HTTP/1.1[0m" 500 -
127.0.0.1 - - [28/Apr/2022 15:23:28] "[37mGET /coinshuffle/start HTTP/1.1[0m" 200 -
127.0.0.1 - - [28/Apr/2022 15:23:28] "[37mGET /mine HTTP/1.1[0m" 200 -
127.0.0.1 - - [28/Apr/2022 15:23:28] "[37mGET /chain HTTP/1.1[0m" 200 -
 * Serving Flask app "client" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Serving Flask app "client" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:6001/ (Press CTRL+C to quit)
 * Running on http://0.0.0.0:6000/ (Press CTRL+C to quit)
 * Serving Flask app "shuffle_server" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:6004/ (Press CTRL+C to quit)
 * Serving Flask app "client" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Serving Flask app "shuffle_server" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "/home/llopin/Projects/coinshuffle/client.py", line 133, in <module>
    app.run(host='0.0.0.0', port=args.port)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 990, in run
    run_simple(host, port, self, **options)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 1052, in run_simple
    inner()
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 996, in inner
    srv = make_server(
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 847, in make_server
    return ThreadedWSGIServer(
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 740, in __init__
    HTTPServer.__init__(self, server_address, handler)
  File "/usr/lib/python3.9/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.9/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.9/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/llopin/Projects/coinshuffle/shuffle_server.py", line 48, in <module>
    run()
  File "/home/llopin/Projects/coinshuffle/shuffle_server.py", line 45, in run
    app.run(host='0.0.0.0', port=args.port)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 990, in run
 * Serving Flask app "client" (lazy loading)
 * Environment: production
    run_simple(host, port, self, **options)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 1052, in run_simple
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
    inner()
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 996, in inner
    srv = make_server(
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 847, in make_server
    return ThreadedWSGIServer(
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 740, in __init__
    HTTPServer.__init__(self, server_address, handler)
  File "/usr/lib/python3.9/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.9/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.9/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/llopin/Projects/coinshuffle/client.py", line 133, in <module>
    app.run(host='0.0.0.0', port=args.port)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 990, in run
    run_simple(host, port, self, **options)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 1052, in run_simple
    inner()
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 996, in inner
    srv = make_server(
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 847, in make_server
    return ThreadedWSGIServer(
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 740, in __init__
    HTTPServer.__init__(self, server_address, handler)
  File "/usr/lib/python3.9/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.9/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.9/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
127.0.0.1 - - [28/Apr/2022 15:24:50] "[37mPOST /coinshuffle/submitkey HTTP/1.1[0m" 201 -
127.0.0.1 - - [28/Apr/2022 15:24:50] "[37mPOST /coinshuffle/new HTTP/1.1[0m" 201 -
127.0.0.1 - - [28/Apr/2022 15:24:50] "[37mPOST /coinshuffle/submitkey HTTP/1.1[0m" 201 -
127.0.0.1 - - [28/Apr/2022 15:24:50] "[37mPOST /coinshuffle/new HTTP/1.1[0m" 201 -
[2022-04-28 15:24:50,597] ERROR in app: Exception on /coinshuffle/initiate [POST]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/llopin/.local/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/llopin/.local/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/llopin/Projects/coinshuffle/client.py", line 109, in post
    node.coin_shuffler.start(json.loads(args['peers']), json.loads(args['order']))
  File "/home/llopin/Projects/coinshuffle/coin_shuffle.py", line 83, in start
    self.encrypted_target = self._encrypt_dest()
  File "/home/llopin/Projects/coinshuffle/coin_shuffle.py", line 119, in _encrypt_dest
    t = util.encrypt(self.order[str(i)], t)
  File "/home/llopin/Projects/coinshuffle/util.py", line 31, in encrypt
    return hexlify(cipher.encrypt(str(msg)))
  File "/home/llopin/.local/lib/python3.9/site-packages/Crypto/Cipher/PKCS1_v1_5.py", line 107, in encrypt
    raise ValueError("Plaintext is too long.")
ValueError: Plaintext is too long.
127.0.0.1 - - [28/Apr/2022 15:24:50] "[35m[1mPOST /coinshuffle/initiate HTTP/1.1[0m" 500 -
[2022-04-28 15:24:50,603] ERROR in app: Exception on /coinshuffle/initiate [POST]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/llopin/.local/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/llopin/.local/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/llopin/Projects/coinshuffle/client.py", line 109, in post
    node.coin_shuffler.start(json.loads(args['peers']), json.loads(args['order']))
  File "/home/llopin/Projects/coinshuffle/coin_shuffle.py", line 83, in start
    self.encrypted_target = self._encrypt_dest()
  File "/home/llopin/Projects/coinshuffle/coin_shuffle.py", line 119, in _encrypt_dest
    t = util.encrypt(self.order[str(i)], t)
  File "/home/llopin/Projects/coinshuffle/util.py", line 31, in encrypt
    return hexlify(cipher.encrypt(str(msg)))
  File "/home/llopin/.local/lib/python3.9/site-packages/Crypto/Cipher/PKCS1_v1_5.py", line 107, in encrypt
    raise ValueError("Plaintext is too long.")
ValueError: Plaintext is too long.
127.0.0.1 - - [28/Apr/2022 15:24:50] "[35m[1mPOST /coinshuffle/initiate HTTP/1.1[0m" 500 -
127.0.0.1 - - [28/Apr/2022 15:24:50] "[37mGET /coinshuffle/start HTTP/1.1[0m" 200 -
127.0.0.1 - - [28/Apr/2022 15:24:50] "[37mGET /mine HTTP/1.1[0m" 200 -
127.0.0.1 - - [28/Apr/2022 15:24:50] "[37mGET /chain HTTP/1.1[0m" 200 -
 * Serving Flask app "client" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Serving Flask app "shuffle_server" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Serving Flask app "client" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:6001/ (Press CTRL+C to quit)
 * Running on http://0.0.0.0:6000/ (Press CTRL+C to quit)
 * Running on http://0.0.0.0:6004/ (Press CTRL+C to quit)
127.0.0.1 - - [28/Apr/2022 15:28:19] "[37mPOST /coinshuffle/submitkey HTTP/1.1[0m" 201 -
127.0.0.1 - - [28/Apr/2022 15:28:19] "[37mPOST /coinshuffle/new HTTP/1.1[0m" 201 -
127.0.0.1 - - [28/Apr/2022 15:28:19] "[37mPOST /coinshuffle/submitkey HTTP/1.1[0m" 201 -
127.0.0.1 - - [28/Apr/2022 15:28:19] "[37mPOST /coinshuffle/new HTTP/1.1[0m" 201 -
[2022-04-28 15:28:19,787] ERROR in app: Exception on /coinshuffle/initiate [POST]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/llopin/.local/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/llopin/.local/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/llopin/Projects/coinshuffle/client.py", line 109, in post
    node.coin_shuffler.start(json.loads(args['peers']), json.loads(args['order']))
  File "/home/llopin/Projects/coinshuffle/coin_shuffle.py", line 83, in start
    self.encrypted_target = self._encrypt_dest()
  File "/home/llopin/Projects/coinshuffle/coin_shuffle.py", line 120, in _encrypt_dest
    t = util.encrypt(self.order[str(i)], t)
  File "/home/llopin/Projects/coinshuffle/util.py", line 30, in encrypt
    return hexlify(cipher.encrypt(str(msg)))
  File "/home/llopin/.local/lib/python3.9/site-packages/Crypto/Cipher/PKCS1_v1_5.py", line 118, in encrypt
    em = b'\x00\x02' + ps + b'\x00' + _copy_bytes(None, None, message)
TypeError: can't concat str to bytes
127.0.0.1 - - [28/Apr/2022 15:28:19] "[35m[1mPOST /coinshuffle/initiate HTTP/1.1[0m" 500 -
[2022-04-28 15:28:19,793] ERROR in app: Exception on /coinshuffle/initiate [POST]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/llopin/.local/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/llopin/.local/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/llopin/Projects/coinshuffle/client.py", line 109, in post
    node.coin_shuffler.start(json.loads(args['peers']), json.loads(args['order']))
  File "/home/llopin/Projects/coinshuffle/coin_shuffle.py", line 83, in start
    self.encrypted_target = self._encrypt_dest()
  File "/home/llopin/Projects/coinshuffle/coin_shuffle.py", line 120, in _encrypt_dest
    t = util.encrypt(self.order[str(i)], t)
  File "/home/llopin/Projects/coinshuffle/util.py", line 30, in encrypt
    return hexlify(cipher.encrypt(str(msg)))
  File "/home/llopin/.local/lib/python3.9/site-packages/Crypto/Cipher/PKCS1_v1_5.py", line 118, in encrypt
    em = b'\x00\x02' + ps + b'\x00' + _copy_bytes(None, None, message)
TypeError: can't concat str to bytes
127.0.0.1 - - [28/Apr/2022 15:28:19] "[35m[1mPOST /coinshuffle/initiate HTTP/1.1[0m" 500 -
127.0.0.1 - - [28/Apr/2022 15:28:19] "[37mGET /coinshuffle/start HTTP/1.1[0m" 200 -
127.0.0.1 - - [28/Apr/2022 15:28:19] "[37mGET /mine HTTP/1.1[0m" 200 -
127.0.0.1 - - [28/Apr/2022 15:28:19] "[37mGET /chain HTTP/1.1[0m" 200 -
 * Serving Flask app "client" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Serving Flask app "client" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:6000/ (Press CTRL+C to quit)
 * Running on http://0.0.0.0:6001/ (Press CTRL+C to quit)
 * Serving Flask app "shuffle_server" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:6004/ (Press CTRL+C to quit)
127.0.0.1 - - [28/Apr/2022 15:29:47] "[37mPOST /coinshuffle/submitkey HTTP/1.1[0m" 201 -
127.0.0.1 - - [28/Apr/2022 15:29:47] "[37mPOST /coinshuffle/new HTTP/1.1[0m" 201 -
127.0.0.1 - - [28/Apr/2022 15:29:48] "[37mPOST /coinshuffle/submitkey HTTP/1.1[0m" 201 -
127.0.0.1 - - [28/Apr/2022 15:29:48] "[37mPOST /coinshuffle/new HTTP/1.1[0m" 201 -
[2022-04-28 15:29:48,109] ERROR in app: Exception on /coinshuffle/initiate [POST]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/llopin/.local/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/llopin/.local/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/llopin/Projects/coinshuffle/client.py", line 109, in post
    node.coin_shuffler.start(json.loads(args['peers']), json.loads(args['order']))
  File "/home/llopin/Projects/coinshuffle/coin_shuffle.py", line 83, in start
    self.encrypted_target = self._encrypt_dest()
  File "/home/llopin/Projects/coinshuffle/coin_shuffle.py", line 120, in _encrypt_dest
    t = util.encrypt(self.order[str(i)], t)
  File "/home/llopin/Projects/coinshuffle/util.py", line 30, in encrypt
    return hexlify(cipher.encrypt(str(msg.encode())))
  File "/home/llopin/.local/lib/python3.9/site-packages/Crypto/Cipher/PKCS1_v1_5.py", line 118, in encrypt
    em = b'\x00\x02' + ps + b'\x00' + _copy_bytes(None, None, message)
TypeError: can't concat str to bytes
127.0.0.1 - - [28/Apr/2022 15:29:48] "[35m[1mPOST /coinshuffle/initiate HTTP/1.1[0m" 500 -
[2022-04-28 15:29:48,114] ERROR in app: Exception on /coinshuffle/initiate [POST]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/llopin/.local/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/llopin/.local/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/llopin/Projects/coinshuffle/client.py", line 109, in post
    node.coin_shuffler.start(json.loads(args['peers']), json.loads(args['order']))
  File "/home/llopin/Projects/coinshuffle/coin_shuffle.py", line 83, in start
    self.encrypted_target = self._encrypt_dest()
  File "/home/llopin/Projects/coinshuffle/coin_shuffle.py", line 120, in _encrypt_dest
    t = util.encrypt(self.order[str(i)], t)
  File "/home/llopin/Projects/coinshuffle/util.py", line 30, in encrypt
    return hexlify(cipher.encrypt(str(msg.encode())))
  File "/home/llopin/.local/lib/python3.9/site-packages/Crypto/Cipher/PKCS1_v1_5.py", line 118, in encrypt
    em = b'\x00\x02' + ps + b'\x00' + _copy_bytes(None, None, message)
TypeError: can't concat str to bytes
127.0.0.1 - - [28/Apr/2022 15:29:48] "[35m[1mPOST /coinshuffle/initiate HTTP/1.1[0m" 500 -
127.0.0.1 - - [28/Apr/2022 15:29:48] "[37mGET /coinshuffle/start HTTP/1.1[0m" 200 -
127.0.0.1 - - [28/Apr/2022 15:29:48] "[37mGET /mine HTTP/1.1[0m" 200 -
127.0.0.1 - - [28/Apr/2022 15:29:48] "[37mGET /chain HTTP/1.1[0m" 200 -
 * Serving Flask app "client" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Serving Flask app "shuffle_server" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Serving Flask app "client" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:6000/ (Press CTRL+C to quit)
 * Running on http://0.0.0.0:6004/ (Press CTRL+C to quit)
 * Running on http://0.0.0.0:6001/ (Press CTRL+C to quit)
127.0.0.1 - - [28/Apr/2022 15:31:22] "[37mPOST /coinshuffle/submitkey HTTP/1.1[0m" 201 -
127.0.0.1 - - [28/Apr/2022 15:31:22] "[37mPOST /coinshuffle/new HTTP/1.1[0m" 201 -
127.0.0.1 - - [28/Apr/2022 15:31:22] "[37mPOST /coinshuffle/submitkey HTTP/1.1[0m" 201 -
127.0.0.1 - - [28/Apr/2022 15:31:22] "[37mPOST /coinshuffle/new HTTP/1.1[0m" 201 -
[2022-04-28 15:31:22,585] ERROR in app: Exception on /coinshuffle/initiate [POST]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/llopin/.local/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/llopin/.local/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/llopin/Projects/coinshuffle/client.py", line 109, in post
    node.coin_shuffler.start(json.loads(args['peers']), json.loads(args['order']))
  File "/home/llopin/Projects/coinshuffle/coin_shuffle.py", line 83, in start
    self.encrypted_target = self._encrypt_dest()
  File "/home/llopin/Projects/coinshuffle/coin_shuffle.py", line 120, in _encrypt_dest
    t = util.encrypt(self.order[str(i)], t)
  File "/home/llopin/Projects/coinshuffle/util.py", line 29, in encrypt
    print(msg.encode())
AttributeError: 'bytes' object has no attribute 'encode'
127.0.0.1 - - [28/Apr/2022 15:31:22] "[35m[1mPOST /coinshuffle/initiate HTTP/1.1[0m" 500 -
[2022-04-28 15:31:22,590] ERROR in app: Exception on /coinshuffle/initiate [POST]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/llopin/.local/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/llopin/.local/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/llopin/Projects/coinshuffle/client.py", line 109, in post
    node.coin_shuffler.start(json.loads(args['peers']), json.loads(args['order']))
  File "/home/llopin/Projects/coinshuffle/coin_shuffle.py", line 83, in start
    self.encrypted_target = self._encrypt_dest()
  File "/home/llopin/Projects/coinshuffle/coin_shuffle.py", line 120, in _encrypt_dest
    t = util.encrypt(self.order[str(i)], t)
  File "/home/llopin/Projects/coinshuffle/util.py", line 29, in encrypt
    print(msg.encode())
AttributeError: 'bytes' object has no attribute 'encode'
127.0.0.1 - - [28/Apr/2022 15:31:22] "[35m[1mPOST /coinshuffle/initiate HTTP/1.1[0m" 500 -
127.0.0.1 - - [28/Apr/2022 15:31:22] "[37mGET /coinshuffle/start HTTP/1.1[0m" 200 -
127.0.0.1 - - [28/Apr/2022 15:31:22] "[37mGET /mine HTTP/1.1[0m" 200 -
127.0.0.1 - - [28/Apr/2022 15:31:22] "[37mGET /chain HTTP/1.1[0m" 200 -
 * Serving Flask app "shuffle_server" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:6004/ (Press CTRL+C to quit)
 * Serving Flask app "client" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Serving Flask app "client" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:6000/ (Press CTRL+C to quit)
 * Running on http://0.0.0.0:6001/ (Press CTRL+C to quit)
127.0.0.1 - - [28/Apr/2022 15:32:35] "[37mPOST /coinshuffle/submitkey HTTP/1.1[0m" 201 -
127.0.0.1 - - [28/Apr/2022 15:32:35] "[37mPOST /coinshuffle/new HTTP/1.1[0m" 201 -
127.0.0.1 - - [28/Apr/2022 15:32:36] "[37mPOST /coinshuffle/submitkey HTTP/1.1[0m" 201 -
127.0.0.1 - - [28/Apr/2022 15:32:36] "[37mPOST /coinshuffle/new HTTP/1.1[0m" 201 -
[2022-04-28 15:32:36,032] ERROR in app: Exception on /coinshuffle/initiate [POST]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/llopin/.local/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/llopin/.local/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/llopin/Projects/coinshuffle/client.py", line 109, in post
    node.coin_shuffler.start(json.loads(args['peers']), json.loads(args['order']))
  File "/home/llopin/Projects/coinshuffle/coin_shuffle.py", line 83, in start
    self.encrypted_target = self._encrypt_dest()
  File "/home/llopin/Projects/coinshuffle/coin_shuffle.py", line 120, in _encrypt_dest
    t = util.encrypt(self.order[str(i)], t)
  File "/home/llopin/Projects/coinshuffle/util.py", line 30, in encrypt
    return hexlify(cipher.encrypt(str(msg).encode()))
  File "/home/llopin/.local/lib/python3.9/site-packages/Crypto/Cipher/PKCS1_v1_5.py", line 107, in encrypt
    raise ValueError("Plaintext is too long.")
ValueError: Plaintext is too long.
127.0.0.1 - - [28/Apr/2022 15:32:36] "[35m[1mPOST /coinshuffle/initiate HTTP/1.1[0m" 500 -
[2022-04-28 15:32:36,038] ERROR in app: Exception on /coinshuffle/initiate [POST]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/llopin/.local/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/llopin/.local/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/llopin/Projects/coinshuffle/client.py", line 109, in post
    node.coin_shuffler.start(json.loads(args['peers']), json.loads(args['order']))
  File "/home/llopin/Projects/coinshuffle/coin_shuffle.py", line 83, in start
    self.encrypted_target = self._encrypt_dest()
  File "/home/llopin/Projects/coinshuffle/coin_shuffle.py", line 120, in _encrypt_dest
    t = util.encrypt(self.order[str(i)], t)
  File "/home/llopin/Projects/coinshuffle/util.py", line 30, in encrypt
    return hexlify(cipher.encrypt(str(msg).encode()))
  File "/home/llopin/.local/lib/python3.9/site-packages/Crypto/Cipher/PKCS1_v1_5.py", line 107, in encrypt
    raise ValueError("Plaintext is too long.")
ValueError: Plaintext is too long.
127.0.0.1 - - [28/Apr/2022 15:32:36] "[35m[1mPOST /coinshuffle/initiate HTTP/1.1[0m" 500 -
127.0.0.1 - - [28/Apr/2022 15:32:36] "[37mGET /coinshuffle/start HTTP/1.1[0m" 200 -
127.0.0.1 - - [28/Apr/2022 15:32:36] "[37mGET /mine HTTP/1.1[0m" 200 -
127.0.0.1 - - [28/Apr/2022 15:32:36] "[37mGET /chain HTTP/1.1[0m" 200 -
 * Serving Flask app "shuffle_server" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Serving Flask app "client" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:6000/ (Press CTRL+C to quit)
 * Running on http://0.0.0.0:6004/ (Press CTRL+C to quit)
 * Serving Flask app "client" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:6001/ (Press CTRL+C to quit)
127.0.0.1 - - [28/Apr/2022 15:47:24] "[37mPOST /coinshuffle/submitkey HTTP/1.1[0m" 201 -
127.0.0.1 - - [28/Apr/2022 15:47:24] "[37mPOST /coinshuffle/new HTTP/1.1[0m" 201 -
127.0.0.1 - - [28/Apr/2022 15:47:24] "[37mPOST /coinshuffle/submitkey HTTP/1.1[0m" 201 -
127.0.0.1 - - [28/Apr/2022 15:47:24] "[37mPOST /coinshuffle/new HTTP/1.1[0m" 201 -
[2022-04-28 15:47:24,406] ERROR in app: Exception on /coinshuffle/initiate [POST]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/llopin/.local/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/llopin/.local/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/llopin/Projects/coinshuffle/client.py", line 109, in post
    node.coin_shuffler.start(json.loads(args['peers']), json.loads(args['order']))
  File "/home/llopin/Projects/coinshuffle/coin_shuffle.py", line 83, in start
    self.encrypted_target = self._encrypt_dest()
  File "/home/llopin/Projects/coinshuffle/coin_shuffle.py", line 120, in _encrypt_dest
    t = util.encrypt(self.order[str(i)], t)
  File "/home/llopin/Projects/coinshuffle/util.py", line 30, in encrypt
    return hexlify(cipher.encrypt(str(msg).encode()))
  File "/home/llopin/.local/lib/python3.9/site-packages/Crypto/Cipher/PKCS1_v1_5.py", line 107, in encrypt
    raise ValueError("Plaintext is too long.")
ValueError: Plaintext is too long.
127.0.0.1 - - [28/Apr/2022 15:47:24] "[35m[1mPOST /coinshuffle/initiate HTTP/1.1[0m" 500 -
[2022-04-28 15:47:24,414] ERROR in app: Exception on /coinshuffle/initiate [POST]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/llopin/.local/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/llopin/.local/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/llopin/Projects/coinshuffle/client.py", line 109, in post
    node.coin_shuffler.start(json.loads(args['peers']), json.loads(args['order']))
  File "/home/llopin/Projects/coinshuffle/coin_shuffle.py", line 83, in start
    self.encrypted_target = self._encrypt_dest()
  File "/home/llopin/Projects/coinshuffle/coin_shuffle.py", line 120, in _encrypt_dest
    t = util.encrypt(self.order[str(i)], t)
  File "/home/llopin/Projects/coinshuffle/util.py", line 30, in encrypt
    return hexlify(cipher.encrypt(str(msg).encode()))
  File "/home/llopin/.local/lib/python3.9/site-packages/Crypto/Cipher/PKCS1_v1_5.py", line 107, in encrypt
    raise ValueError("Plaintext is too long.")
ValueError: Plaintext is too long.
127.0.0.1 - - [28/Apr/2022 15:47:24] "[35m[1mPOST /coinshuffle/initiate HTTP/1.1[0m" 500 -
127.0.0.1 - - [28/Apr/2022 15:47:24] "[37mGET /coinshuffle/start HTTP/1.1[0m" 200 -
127.0.0.1 - - [28/Apr/2022 15:47:24] "[37mGET /mine HTTP/1.1[0m" 200 -
127.0.0.1 - - [28/Apr/2022 15:47:24] "[37mGET /chain HTTP/1.1[0m" 200 -
 * Serving Flask app "client" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Serving Flask app "client" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:6000/ (Press CTRL+C to quit)
 * Running on http://0.0.0.0:6001/ (Press CTRL+C to quit)
127.0.0.1 - - [28/Apr/2022 16:07:18] "[37mPOST /coinshuffle/new HTTP/1.1[0m" 201 -
127.0.0.1 - - [28/Apr/2022 16:07:18] "[37mPOST /coinshuffle/new HTTP/1.1[0m" 201 -
[2022-04-28 16:07:18,046] ERROR in app: Exception on /coinshuffle/initiate [POST]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/llopin/.local/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/llopin/.local/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/llopin/Projects/coinshuffle/client.py", line 109, in post
    node.coin_shuffler.start(json.loads(args['peers']), json.loads(args['order']))
  File "/home/llopin/Projects/coinshuffle/coin_shuffle.py", line 83, in start
    self.encrypted_target = self._encrypt_dest()
  File "/home/llopin/Projects/coinshuffle/coin_shuffle.py", line 120, in _encrypt_dest
    t = util.encrypt(self.order[str(i)], t)
  File "/home/llopin/Projects/coinshuffle/util.py", line 30, in encrypt
    return hexlify(cipher.encrypt(str(msg).encode()))
  File "/home/llopin/.local/lib/python3.9/site-packages/Crypto/Cipher/PKCS1_v1_5.py", line 107, in encrypt
    raise ValueError("Plaintext is too long.")
ValueError: Plaintext is too long.
127.0.0.1 - - [28/Apr/2022 16:07:18] "[35m[1mPOST /coinshuffle/initiate HTTP/1.1[0m" 500 -
[2022-04-28 16:07:18,054] ERROR in app: Exception on /coinshuffle/initiate [POST]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/llopin/.local/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/llopin/.local/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/llopin/Projects/coinshuffle/client.py", line 109, in post
    node.coin_shuffler.start(json.loads(args['peers']), json.loads(args['order']))
  File "/home/llopin/Projects/coinshuffle/coin_shuffle.py", line 83, in start
    self.encrypted_target = self._encrypt_dest()
  File "/home/llopin/Projects/coinshuffle/coin_shuffle.py", line 120, in _encrypt_dest
    t = util.encrypt(self.order[str(i)], t)
  File "/home/llopin/Projects/coinshuffle/util.py", line 30, in encrypt
    return hexlify(cipher.encrypt(str(msg).encode()))
  File "/home/llopin/.local/lib/python3.9/site-packages/Crypto/Cipher/PKCS1_v1_5.py", line 107, in encrypt
    raise ValueError("Plaintext is too long.")
ValueError: Plaintext is too long.
127.0.0.1 - - [28/Apr/2022 16:07:18] "[35m[1mPOST /coinshuffle/initiate HTTP/1.1[0m" 500 -
127.0.0.1 - - [28/Apr/2022 16:07:18] "[37mGET /mine HTTP/1.1[0m" 200 -
127.0.0.1 - - [28/Apr/2022 16:07:18] "[37mGET /chain HTTP/1.1[0m" 200 -
 * Serving Flask app "client" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Serving Flask app "client" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:6000/ (Press CTRL+C to quit)
 * Running on http://0.0.0.0:6001/ (Press CTRL+C to quit)
[2022-04-28 16:08:13,255] ERROR in app: Exception on /coinshuffle/new [POST]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.9/http/client.py", line 1279, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1325, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1274, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1034, in _send_output
    self.send(msg)
  File "/usr/lib/python3.9/http/client.py", line 974, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 200, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f35cf8c74f0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='0.0.0.0', port=6004): Max retries exceeded with url: /coinshuffle/submitkey (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f35cf8c74f0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/llopin/.local/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/llopin/.local/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/llopin/Projects/coinshuffle/client.py", line 89, in post
    node.new_coin_shuffle(args['source'], args['hidden_target'],
  File "/home/llopin/Projects/coinshuffle/Node.py", line 62, in new_coin_shuffle
    self.coin_shuffler = CoinShuffleClient(self, self.addr, source, hidden_target, server_addr)
  File "/home/llopin/Projects/coinshuffle/coin_shuffle.py", line 63, in __init__
    self.submit_ek_to_server(server_addr)
  File "/home/llopin/Projects/coinshuffle/coin_shuffle.py", line 68, in submit_ek_to_server
    requests.post(addr + '/coinshuffle/submitkey', data = {'public_key' : self.ek, 'address' : self.addr})
  File "/usr/lib/python3/dist-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='0.0.0.0', port=6004): Max retries exceeded with url: /coinshuffle/submitkey (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f35cf8c74f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
127.0.0.1 - - [28/Apr/2022 16:08:13] "[35m[1mPOST /coinshuffle/new HTTP/1.1[0m" 500 -
[2022-04-28 16:08:13,349] ERROR in app: Exception on /coinshuffle/new [POST]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.9/http/client.py", line 1279, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1325, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1274, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1034, in _send_output
    self.send(msg)
  File "/usr/lib/python3.9/http/client.py", line 974, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 200, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f95e9868400>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='0.0.0.0', port=6004): Max retries exceeded with url: /coinshuffle/submitkey (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f95e9868400>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/llopin/.local/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/llopin/.local/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/llopin/Projects/coinshuffle/client.py", line 89, in post
    node.new_coin_shuffle(args['source'], args['hidden_target'],
  File "/home/llopin/Projects/coinshuffle/Node.py", line 62, in new_coin_shuffle
    self.coin_shuffler = CoinShuffleClient(self, self.addr, source, hidden_target, server_addr)
  File "/home/llopin/Projects/coinshuffle/coin_shuffle.py", line 63, in __init__
    self.submit_ek_to_server(server_addr)
  File "/home/llopin/Projects/coinshuffle/coin_shuffle.py", line 68, in submit_ek_to_server
    requests.post(addr + '/coinshuffle/submitkey', data = {'public_key' : self.ek, 'address' : self.addr})
  File "/usr/lib/python3/dist-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='0.0.0.0', port=6004): Max retries exceeded with url: /coinshuffle/submitkey (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f95e9868400>: Failed to establish a new connection: [Errno 111] Connection refused'))
127.0.0.1 - - [28/Apr/2022 16:08:13] "[35m[1mPOST /coinshuffle/new HTTP/1.1[0m" 500 -
127.0.0.1 - - [28/Apr/2022 16:08:13] "[37mGET /mine HTTP/1.1[0m" 200 -
127.0.0.1 - - [28/Apr/2022 16:08:13] "[37mGET /chain HTTP/1.1[0m" 200 -
 * Serving Flask app "client" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:6000/ (Press CTRL+C to quit)
 * Serving Flask app "client" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:6001/ (Press CTRL+C to quit)
127.0.0.1 - - [28/Apr/2022 16:08:28] "[37mPOST /coinshuffle/new HTTP/1.1[0m" 201 -
127.0.0.1 - - [28/Apr/2022 16:08:28] "[37mPOST /coinshuffle/new HTTP/1.1[0m" 201 -
[2022-04-28 16:08:28,493] ERROR in app: Exception on /coinshuffle/initiate [POST]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/llopin/.local/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/llopin/.local/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/llopin/Projects/coinshuffle/client.py", line 109, in post
    node.coin_shuffler.start(json.loads(args['peers']), json.loads(args['order']))
  File "/home/llopin/Projects/coinshuffle/coin_shuffle.py", line 83, in start
    self.encrypted_target = self._encrypt_dest()
  File "/home/llopin/Projects/coinshuffle/coin_shuffle.py", line 120, in _encrypt_dest
    t = util.encrypt(self.order[str(i)], t)
  File "/home/llopin/Projects/coinshuffle/util.py", line 30, in encrypt
    return hexlify(cipher.encrypt(str(msg).encode()))
  File "/home/llopin/.local/lib/python3.9/site-packages/Crypto/Cipher/PKCS1_v1_5.py", line 107, in encrypt
    raise ValueError("Plaintext is too long.")
ValueError: Plaintext is too long.
127.0.0.1 - - [28/Apr/2022 16:08:28] "[35m[1mPOST /coinshuffle/initiate HTTP/1.1[0m" 500 -
[2022-04-28 16:08:28,503] ERROR in app: Exception on /coinshuffle/initiate [POST]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/llopin/.local/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/llopin/.local/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/llopin/Projects/coinshuffle/client.py", line 109, in post
    node.coin_shuffler.start(json.loads(args['peers']), json.loads(args['order']))
  File "/home/llopin/Projects/coinshuffle/coin_shuffle.py", line 83, in start
    self.encrypted_target = self._encrypt_dest()
  File "/home/llopin/Projects/coinshuffle/coin_shuffle.py", line 120, in _encrypt_dest
    t = util.encrypt(self.order[str(i)], t)
  File "/home/llopin/Projects/coinshuffle/util.py", line 30, in encrypt
    return hexlify(cipher.encrypt(str(msg).encode()))
  File "/home/llopin/.local/lib/python3.9/site-packages/Crypto/Cipher/PKCS1_v1_5.py", line 107, in encrypt
    raise ValueError("Plaintext is too long.")
ValueError: Plaintext is too long.
127.0.0.1 - - [28/Apr/2022 16:08:28] "[35m[1mPOST /coinshuffle/initiate HTTP/1.1[0m" 500 -
127.0.0.1 - - [28/Apr/2022 16:08:28] "[37mGET /mine HTTP/1.1[0m" 200 -
127.0.0.1 - - [28/Apr/2022 16:08:28] "[37mGET /chain HTTP/1.1[0m" 200 -
 * Serving Flask app "client" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Serving Flask app "client" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:6000/ (Press CTRL+C to quit)
 * Running on http://0.0.0.0:6001/ (Press CTRL+C to quit)
127.0.0.1 - - [28/Apr/2022 16:10:55] "[37mPOST /coinshuffle/new HTTP/1.1[0m" 201 -
127.0.0.1 - - [28/Apr/2022 16:10:55] "[37mPOST /coinshuffle/new HTTP/1.1[0m" 201 -
[2022-04-28 16:10:55,431] ERROR in app: Exception on /coinshuffle/initiate [POST]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/llopin/.local/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/llopin/.local/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/llopin/Projects/coinshuffle/client.py", line 109, in post
    node.coin_shuffler.start(json.loads(args['peers']), json.loads(args['order']))
  File "/home/llopin/Projects/coinshuffle/coin_shuffle.py", line 83, in start
    self.encrypted_target = self._encrypt_dest()
  File "/home/llopin/Projects/coinshuffle/coin_shuffle.py", line 120, in _encrypt_dest
    t = util.encrypt(self.order[str(i)], t)
  File "/home/llopin/Projects/coinshuffle/util.py", line 30, in encrypt
    return hexlify(cipher.encrypt(str(msg).encode()))
  File "/home/llopin/.local/lib/python3.9/site-packages/Crypto/Cipher/PKCS1_v1_5.py", line 107, in encrypt
    raise ValueError("Plaintext is too long.")
ValueError: Plaintext is too long.
127.0.0.1 - - [28/Apr/2022 16:10:55] "[35m[1mPOST /coinshuffle/initiate HTTP/1.1[0m" 500 -
[2022-04-28 16:10:55,442] ERROR in app: Exception on /coinshuffle/initiate [POST]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/llopin/.local/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/llopin/.local/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/llopin/Projects/coinshuffle/client.py", line 109, in post
    node.coin_shuffler.start(json.loads(args['peers']), json.loads(args['order']))
  File "/home/llopin/Projects/coinshuffle/coin_shuffle.py", line 83, in start
    self.encrypted_target = self._encrypt_dest()
  File "/home/llopin/Projects/coinshuffle/coin_shuffle.py", line 120, in _encrypt_dest
    t = util.encrypt(self.order[str(i)], t)
  File "/home/llopin/Projects/coinshuffle/util.py", line 30, in encrypt
    return hexlify(cipher.encrypt(str(msg).encode()))
  File "/home/llopin/.local/lib/python3.9/site-packages/Crypto/Cipher/PKCS1_v1_5.py", line 107, in encrypt
    raise ValueError("Plaintext is too long.")
ValueError: Plaintext is too long.
127.0.0.1 - - [28/Apr/2022 16:10:55] "[35m[1mPOST /coinshuffle/initiate HTTP/1.1[0m" 500 -
127.0.0.1 - - [28/Apr/2022 16:10:55] "[37mGET /mine HTTP/1.1[0m" 200 -
127.0.0.1 - - [28/Apr/2022 16:10:55] "[37mGET /chain HTTP/1.1[0m" 200 -
 * Serving Flask app "client" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Serving Flask app "client" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:6000/ (Press CTRL+C to quit)
 * Running on http://0.0.0.0:6001/ (Press CTRL+C to quit)
127.0.0.1 - - [28/Apr/2022 16:11:25] "[37mPOST /coinshuffle/new HTTP/1.1[0m" 201 -
127.0.0.1 - - [28/Apr/2022 16:11:25] "[37mPOST /coinshuffle/new HTTP/1.1[0m" 201 -
127.0.0.1 - - [28/Apr/2022 16:12:04] "[37mGET /mine HTTP/1.1[0m" 200 -
127.0.0.1 - - [28/Apr/2022 16:12:04] "[37mGET /chain HTTP/1.1[0m" 200 -
 * Serving Flask app "client" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Serving Flask app "client" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:6001/ (Press CTRL+C to quit)
 * Running on http://0.0.0.0:6000/ (Press CTRL+C to quit)
127.0.0.1 - - [28/Apr/2022 16:13:01] "[37mPOST /coinshuffle/new HTTP/1.1[0m" 201 -
127.0.0.1 - - [28/Apr/2022 16:13:01] "[37mPOST /coinshuffle/new HTTP/1.1[0m" 201 -
127.0.0.1 - - [28/Apr/2022 16:13:12] "[37mGET /mine HTTP/1.1[0m" 200 -
127.0.0.1 - - [28/Apr/2022 16:13:12] "[37mGET /chain HTTP/1.1[0m" 200 -
 * Serving Flask app "client" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Serving Flask app "client" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Serving Flask app "client" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:6002/ (Press CTRL+C to quit)
 * Running on http://0.0.0.0:6001/ (Press CTRL+C to quit)
 * Running on http://0.0.0.0:6000/ (Press CTRL+C to quit)
127.0.0.1 - - [28/Apr/2022 16:23:19] "[37mPOST /transactions/new HTTP/1.1[0m" 200 -
127.0.0.1 - - [28/Apr/2022 16:23:19] "[37mGET /mine HTTP/1.1[0m" 200 -
127.0.0.1 - - [28/Apr/2022 16:23:19] "[37mGET //chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [28/Apr/2022 16:23:19] "[37mGET //chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [28/Apr/2022 16:23:19] "[37mGET /resolve HTTP/1.1[0m" 200 -
127.0.0.1 - - [28/Apr/2022 16:23:19] "[37mGET /chain HTTP/1.1[0m" 200 -
 * Serving Flask app "client" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Serving Flask app "client" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Serving Flask app "client" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:6000/ (Press CTRL+C to quit)
 * Running on http://0.0.0.0:6002/ (Press CTRL+C to quit)
 * Running on http://0.0.0.0:6001/ (Press CTRL+C to quit)
127.0.0.1 - - [28/Apr/2022 16:25:03] "[37mPOST /transactions/new HTTP/1.1[0m" 200 -
127.0.0.1 - - [28/Apr/2022 16:25:03] "[37mGET /mine HTTP/1.1[0m" 200 -
127.0.0.1 - - [28/Apr/2022 16:25:03] "[37mGET //chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [28/Apr/2022 16:25:03] "[37mGET //chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [28/Apr/2022 16:25:03] "[37mGET /resolve HTTP/1.1[0m" 200 -
127.0.0.1 - - [28/Apr/2022 16:25:03] "[37mGET /chain HTTP/1.1[0m" 200 -
 * Serving Flask app "client" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Serving Flask app "client" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Serving Flask app "client" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:6000/ (Press CTRL+C to quit)
 * Running on http://0.0.0.0:6002/ (Press CTRL+C to quit)
 * Running on http://0.0.0.0:6001/ (Press CTRL+C to quit)
127.0.0.1 - - [28/Apr/2022 16:25:31] "[37mPOST /transactions/new HTTP/1.1[0m" 200 -
127.0.0.1 - - [28/Apr/2022 16:25:31] "[37mGET /mine HTTP/1.1[0m" 200 -
127.0.0.1 - - [28/Apr/2022 16:25:31] "[37mGET //chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [28/Apr/2022 16:25:31] "[37mGET //chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [28/Apr/2022 16:25:31] "[37mGET /resolve HTTP/1.1[0m" 200 -
127.0.0.1 - - [28/Apr/2022 16:25:31] "[37mGET /chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [28/Apr/2022 16:27:51] "[31m[1mGET /coinshuffle/new HTTP/1.1[0m" 405 -
127.0.0.1 - - [28/Apr/2022 16:27:52] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
127.0.0.1 - - [28/Apr/2022 16:28:15] "[31m[1mGET /coinshuffle/new HTTP/1.1[0m" 405 -
127.0.0.1 - - [28/Apr/2022 16:28:20] "[31m[1mGET /coinshuffle/new HTTP/1.1[0m" 405 -
127.0.0.1 - - [28/Apr/2022 16:28:20] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
 * Serving Flask app "client" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Serving Flask app "client" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "/home/llopin/Projects/coinshuffle/client.py", line 133, in <module>
    app.run(host='0.0.0.0', port=args.port)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 990, in run
    run_simple(host, port, self, **options)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 1052, in run_simple
    inner()
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 996, in inner
    srv = make_server(
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 847, in make_server
    return ThreadedWSGIServer(
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 740, in __init__
    HTTPServer.__init__(self, server_address, handler)
  File "/usr/lib/python3.9/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.9/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.9/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/llopin/Projects/coinshuffle/client.py", line 133, in <module>
    app.run(host='0.0.0.0', port=args.port)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 990, in run
    run_simple(host, port, self, **options)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 1052, in run_simple
    inner()
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 996, in inner
    srv = make_server(
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 847, in make_server
    return ThreadedWSGIServer(
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 740, in __init__
    HTTPServer.__init__(self, server_address, handler)
  File "/usr/lib/python3.9/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.9/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.9/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
127.0.0.1 - - [28/Apr/2022 16:29:39] "[37mPOST /coinshuffle/new HTTP/1.1[0m" 201 -
127.0.0.1 - - [28/Apr/2022 16:29:39] "[37mPOST /coinshuffle/new HTTP/1.1[0m" 201 -
 * Serving Flask app "client" (lazy loading)
 * Serving Flask app "client" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "/home/llopin/Projects/coinshuffle/client.py", line 133, in <module>
    app.run(host='0.0.0.0', port=args.port)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 990, in run
    run_simple(host, port, self, **options)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 1052, in run_simple
    inner()
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 996, in inner
    srv = make_server(
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 847, in make_server
    return ThreadedWSGIServer(
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 740, in __init__
    HTTPServer.__init__(self, server_address, handler)
  File "/usr/lib/python3.9/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.9/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.9/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/llopin/Projects/coinshuffle/client.py", line 133, in <module>
    app.run(host='0.0.0.0', port=args.port)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 990, in run
    run_simple(host, port, self, **options)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 1052, in run_simple
    inner()
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 996, in inner
    srv = make_server(
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 847, in make_server
    return ThreadedWSGIServer(
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 740, in __init__
    HTTPServer.__init__(self, server_address, handler)
  File "/usr/lib/python3.9/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.9/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.9/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
 * Serving Flask app "client" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "/home/llopin/Projects/coinshuffle/client.py", line 133, in <module>
    app.run(host='0.0.0.0', port=args.port)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 990, in run
    run_simple(host, port, self, **options)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 1052, in run_simple
    inner()
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 996, in inner
    srv = make_server(
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 847, in make_server
    return ThreadedWSGIServer(
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 740, in __init__
    HTTPServer.__init__(self, server_address, handler)
  File "/usr/lib/python3.9/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.9/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.9/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
127.0.0.1 - - [28/Apr/2022 16:33:59] "[37mPOST /transactions/new HTTP/1.1[0m" 200 -
127.0.0.1 - - [28/Apr/2022 16:33:59] "[37mGET /mine HTTP/1.1[0m" 200 -
127.0.0.1 - - [28/Apr/2022 16:33:59] "[37mGET //chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [28/Apr/2022 16:33:59] "[37mGET //chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [28/Apr/2022 16:33:59] "[37mGET /resolve HTTP/1.1[0m" 200 -
127.0.0.1 - - [28/Apr/2022 16:33:59] "[37mGET /chain HTTP/1.1[0m" 200 -
 * Serving Flask app "client" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Serving Flask app "client" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Serving Flask app "client" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:6000/ (Press CTRL+C to quit)
 * Running on http://0.0.0.0:6002/ (Press CTRL+C to quit)
 * Running on http://0.0.0.0:6001/ (Press CTRL+C to quit)
127.0.0.1 - - [28/Apr/2022 16:35:07] "[37mPOST /transactions/new HTTP/1.1[0m" 200 -
127.0.0.1 - - [28/Apr/2022 16:35:07] "[37mGET /mine HTTP/1.1[0m" 200 -
127.0.0.1 - - [28/Apr/2022 16:35:07] "[37mGET //chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [28/Apr/2022 16:35:07] "[37mGET //chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [28/Apr/2022 16:35:07] "[37mGET /resolve HTTP/1.1[0m" 200 -
127.0.0.1 - - [28/Apr/2022 16:35:07] "[37mGET /chain HTTP/1.1[0m" 200 -
127.0.0.1 - - [28/Apr/2022 17:15:58] "[37mPOST /coinshuffle/new HTTP/1.1[0m" 201 -
127.0.0.1 - - [28/Apr/2022 17:21:11] "[37mPOST /coinshuffle/new HTTP/1.1[0m" 201 -
[2022-04-28 17:23:32,025] ERROR in app: Exception on /coinshuffle/initiate [POST]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/llopin/.local/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/llopin/.local/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/llopin/Projects/coinshuffle/client.py", line 109, in post
    args = ss_parser.parse_args()
  File "/home/llopin/Projects/coinshuffle/coin_shuffle.py", line 83, in start
    self.encrypted_target = self._encrypt_dest()
  File "/home/llopin/Projects/coinshuffle/coin_shuffle.py", line 120, in _encrypt_dest
    t = util.encrypt(self.order[str(i)], t)
  File "/home/llopin/Projects/coinshuffle/util.py", line 30, in encrypt
    return hexlify(cipher.encrypt(str(msg).encode()))
  File "/home/llopin/.local/lib/python3.9/site-packages/Crypto/Cipher/PKCS1_v1_5.py", line 107, in encrypt
    raise ValueError("Plaintext is too long.")
ValueError: Plaintext is too long.
127.0.0.1 - - [28/Apr/2022 17:23:32] "[35m[1mPOST /coinshuffle/initiate HTTP/1.1[0m" 500 -
